### PR TITLE
Update references and icons for ksp-1.8

### PR DESCRIPTION
**Pull request by whale2**
Add solution and project files
Add proper Unity references
Rename icon texture files so they are properly displayed

### CODE REVIEW

**Comment by markusa380** [comment]
I have added you as a collaborator, so you have full control. If you want to release it e.g. on Spacedock just let me know.

**Comment by whale2** [comment]
Hi,

Thanks for adding me.
As for Spacedock - yes, I think it perfectly sensible to make a release
there, but my first concern here is CKAN as preferred source of stuff for
Realism Overhaul.
On the other hand, Spacedock releases are picked up by CKAN automatically,
so maybe two birds with one stone :)

I will make a github release then and wrote you back about Spacedock.
Thanks again.

**Comment by markusa380** [comment]
@whale2 Correct, CKAN uses SpaceDock for PersistentRotation, so we should be good.

**Comment by whale2** [comment]
Two more things -
- I'm thinking about adding MiniAVC to the mix, but it requires mentioning
explicitly in forum post and in other things like SpaceDock that it is
being used - what do you think of it?
- Do you still have time/motivation to support the mod? If yes, that's just
great, if not - all my requests might be a sort of a burden to you.

Thanks

**Comment by markusa380** [comment]
MiniAVC sounds like a good idea.

I still maintain this repository and the community sites like SpaceDock and the forum, allthough I since have moved on from developing the mod myself. So your requests aren't a burden but instead valuable contributions to this otherwise dormant project.

**Comment by whale2** [comment]
Great, then I'll just make a PR for those changes.
Thanks again.

Markus Appel <notifications@github.com> schrieb am Mi., 19. Feb. 2020,
10:49:

**Comment by RCrockford** [comment]
MiniAVC is not a good idea:
https://forum.kerbalspaceprogram.com/index.php?/topic/191568-important-announcement-about-miniavc-and-zerominiavc

**Comment by whale2** [comment]
Damn, that hurts!

Ok, then just .version file for full AVC plugin? What else - .netkan?

**Comment by siimav** [comment]
> Ok, then just .version file for full AVC plugin? What else - .netkan?

Adding a .version file makes sense. In addition to that you would probably also want to increment `AssemblyFileVersion` in AssemblyInfo.cs. I'm not sure how CKAN handles Spacedock releases so it's possible that you would need to also PR a change to the netkan file.

**Comment by whale2** [comment]
> I have added you as a collaborator, so you have full control. If you want to release it e.g. on Spacedock just let me know.

Github still does not let me merge the PR...

**Comment by markusa380** [comment]
Merged. @whale2 GitHub tells me that you haven't actually accepted the invitiation yet, so that's maybe why. ;)

**Comment by whale2** [comment]
> Merged. @whale2 GitHub tells me that you haven't actually accepted the invitiation yet, so that's maybe why. ;)

Damn. I feel silly and that's not the first time :(
Anyway, thanks for merging.

**Comment by whale2** [comment]
@markusa380, tried to reach you by e-mail, not sure if it's worked. Can we please make a SpaceDock release?

**Comment by markusa380** [comment]
@whale2 Okay! Unfortunately, I am not able to build the project currently. Can you create the package (use the ones on SpaceDock as an example) and send it to me? :)

**Comment by whale2** [comment]
Sure thing, will do.

**Pull request merged**
