### PR TITLE
Fix #19 and other issues.

### LINKED ISSUE #19: Orbit changes upon exiting timewarp while rotating
The orbit of the vessel changes upon exiting timewarp while rotating. This seems to depend on the distribution of mass of the vessel and the rotation rate.

Tested in fresh install of KSP 1.2.2 Win64 with PersistentRotation from commit 2d7aebad8bfd56b69bc6d4a5cdf7bf0aff05fe79.

Here is a video demonstrating the effect:
https://youtu.be/fx6-FmRAQWI

### PR DESCRIPTION
**Pull request by Virindi-AC**
Fixes:
- #19 This issue is not caused by floating point integration but rather has two causes. One, at resumption of physics, angular momentum is reapplied based on the center of each part rather than the center of mass of each part. Two, this must be applied at least one frame later or the physics system does not handle it properly.
- Previously, leaving timewarp resulted in a small slowing of rotational velocity. This is because when spinning, the vessel's joints are stretched outwards, but while on rails the joints are reset. Thus, applying the same angular VELOCITY results in a lower angular MOMENTUM of the craft as a whole. To fix this, instead persist angular momentum rather than velocity, which causes the vessel to spin its joints back up, except...
- By default, each rigidbody has a maximum angular velocity of 50. This means that if the above were done without correction, a vessel entering timewarp at maximum rotation would exit and we would attempt to apply a higher than maximum angular velocity to the parts, which would be clamped. To avoid this, when applying the higher angular velocity we must temporarily increase the maximum rotation rate of rigidbodies for a time long enough for the vessel's joints to re-stretch.
- When doing the above it was noted that for approximately the first three ticks after exiting timewarp, the vessel's moment of inertia was wildly incorrect. So a 4-tick delay was added before reapplying angular momentum.
- Note: I replaced the existing "momentum" variable (which contained angular VELOCITY) with angular momentum. Thus, loading existing save files will restore vessels at a much slower rate the first time.

### CODE REVIEW

**Comment by markusa380** [comment]
I'll look into it, but up until now I didn't realize that this exists. I am not too active with PR anymore.

**Comment by markusa380** [comment]
Thanks for working on the mod, I feel honored.

**Review by markusa380 — APPROVED** [review]

**Comment by markusa380** [comment]
You made a pretty bad bug. You don't divide the Angular Momentum through the mass of the vessel when in spinning in timewarp.

**Comment by Virindi-AC** [comment]
Sorry about that. I guess it's hard to tell if your spin rate is correct when on rails because the display is fast. Oh well. Glad you noticed that :)

**Pull request merged**
